package it.unisalento.SWEng_project.domain;

// Generated 16-mar-2016 14.43.11 by Hibernate Tools 4.3.1

/**
 * AddressBook generated by hbm2java
 */
public class AddressBook implements java.io.Serializable {

	private int userId;
	private User user;
	private String type;
	private String contact;

	public AddressBook() {
	}

	public AddressBook(User user) {
		this.user = user;
	}

	public AddressBook(User user, String type, String contact) {
		this.user = user;
		this.type = type;
		this.contact = contact;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

}
