package it.unisalento.SWEng_project.domain;

// Generated 16-mar-2016 14.43.11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set typeOfProducts = new HashSet(0);

	public Category() {
	}

	public Category(String name, Set typeOfProducts) {
		this.name = name;
		this.typeOfProducts = typeOfProducts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTypeOfProducts() {
		return this.typeOfProducts;
	}

	public void setTypeOfProducts(Set typeOfProducts) {
		this.typeOfProducts = typeOfProducts;
	}

}
