package it.unisalento.SWEng_project.domain;

// Generated 18-mar-2016 23.51.26 by Hibernate Tools 4.3.1

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int productId;
	private Product product;
	private String ramType;
	private String ramSize;
	private String cpuFreq;
	private String cpuBrand;
	private String cpuModel;
	private String cache;
	private String screenSize;
	private String storageBrand;
	private String storageModel;
	private String storageType;
	private String storageSize;

	public Device() {
	}

	public Device(Product product) {
		this.product = product;
	}

	public Device(Product product, String ramType, String ramSize,
			String cpuFreq, String cpuBrand, String cpuModel, String cache,
			String screenSize, String storageBrand, String storageModel,
			String storageType, String storageSize) {
		this.product = product;
		this.ramType = ramType;
		this.ramSize = ramSize;
		this.cpuFreq = cpuFreq;
		this.cpuBrand = cpuBrand;
		this.cpuModel = cpuModel;
		this.cache = cache;
		this.screenSize = screenSize;
		this.storageBrand = storageBrand;
		this.storageModel = storageModel;
		this.storageType = storageType;
		this.storageSize = storageSize;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getRamType() {
		return this.ramType;
	}

	public void setRamType(String ramType) {
		this.ramType = ramType;
	}

	public String getRamSize() {
		return this.ramSize;
	}

	public void setRamSize(String ramSize) {
		this.ramSize = ramSize;
	}

	public String getCpuFreq() {
		return this.cpuFreq;
	}

	public void setCpuFreq(String cpuFreq) {
		this.cpuFreq = cpuFreq;
	}

	public String getCpuBrand() {
		return this.cpuBrand;
	}

	public void setCpuBrand(String cpuBrand) {
		this.cpuBrand = cpuBrand;
	}

	public String getCpuModel() {
		return this.cpuModel;
	}

	public void setCpuModel(String cpuModel) {
		this.cpuModel = cpuModel;
	}

	public String getCache() {
		return this.cache;
	}

	public void setCache(String cache) {
		this.cache = cache;
	}

	public String getScreenSize() {
		return this.screenSize;
	}

	public void setScreenSize(String screenSize) {
		this.screenSize = screenSize;
	}

	public String getStorageBrand() {
		return this.storageBrand;
	}

	public void setStorageBrand(String storageBrand) {
		this.storageBrand = storageBrand;
	}

	public String getStorageModel() {
		return this.storageModel;
	}

	public void setStorageModel(String storageModel) {
		this.storageModel = storageModel;
	}

	public String getStorageType() {
		return this.storageType;
	}

	public void setStorageType(String storageType) {
		this.storageType = storageType;
	}

	public String getStorageSize() {
		return this.storageSize;
	}

	public void setStorageSize(String storageSize) {
		this.storageSize = storageSize;
	}

}
