package it.unisalento.SWEng_project.domain;

// Generated 15-mar-2016 15.20.49 by Hibernate Tools 4.3.1

/**
 * IncludesId generated by hbm2java
 */
public class IncludesId implements java.io.Serializable {

	private int orderId;
	private int shopId;
	private int productId;

	public IncludesId() {
	}

	public IncludesId(int orderId, int shopId, int productId) {
		this.orderId = orderId;
		this.shopId = shopId;
		this.productId = productId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IncludesId))
			return false;
		IncludesId castOther = (IncludesId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getShopId() == castOther.getShopId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getShopId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
