package it.unisalento.SWEng_project.domain;

// Generated 16-mar-2016 14.43.11 by Hibernate Tools 4.3.1

/**
 * LocationId generated by hbm2java
 */
public class LocationId implements java.io.Serializable {

	private String name;
	private int userId;

	public LocationId() {
	}

	public LocationId(String name, int userId) {
		this.name = name;
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationId))
			return false;
		LocationId castOther = (LocationId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getUserId();
		return result;
	}

}
