package it.unisalento.SWEng_project.domain;

// Generated 18-mar-2016 23.51.26 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private User user;
	private Date timePayment;
	private BigDecimal totalPrice;
	private String tipology;
	private Set shipments = new HashSet(0);
	private Set includeses = new HashSet(0);

	public Order() {
	}

	public Order(User user) {
		this.user = user;
	}

	public Order(User user, Date timePayment, BigDecimal totalPrice,
			String tipology, Set shipments, Set includeses) {
		this.user = user;
		this.timePayment = timePayment;
		this.totalPrice = totalPrice;
		this.tipology = tipology;
		this.shipments = shipments;
		this.includeses = includeses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getTimePayment() {
		return this.timePayment;
	}

	public void setTimePayment(Date timePayment) {
		this.timePayment = timePayment;
	}

	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getTipology() {
		return this.tipology;
	}

	public void setTipology(String tipology) {
		this.tipology = tipology;
	}

	public Set getShipments() {
		return this.shipments;
	}

	public void setShipments(Set shipments) {
		this.shipments = shipments;
	}

	public Set getIncludeses() {
		return this.includeses;
	}

	public void setIncludeses(Set includeses) {
		this.includeses = includeses;
	}

}
