package it.unisalento.SWEng_project.domain;

<<<<<<< HEAD
// Generated 21-mar-2016 17.28.49 by Hibernate Tools 4.3.1
=======
// Generated 18-mar-2016 23.51.26 by Hibernate Tools 4.3.1
>>>>>>> refs/remotes/origin/master

/**
 * ProductPhoto generated by hbm2java
 */
public class ProductPhoto implements java.io.Serializable {

	private ProductPhotoId id;
	private Product product;

	public ProductPhoto() {
	}

	public ProductPhoto(ProductPhotoId id, Product product) {
		this.id = id;
		this.product = product;
	}

	public ProductPhotoId getId() {
		return this.id;
	}

	public void setId(ProductPhotoId id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
