package it.unisalento.SWEng_project.domain;

<<<<<<< HEAD
// Generated 21-mar-2016 17.28.49 by Hibernate Tools 4.3.1
=======
// Generated 18-mar-2016 23.51.26 by Hibernate Tools 4.3.1
>>>>>>> refs/remotes/origin/master

/**
 * ProductPhotoId generated by hbm2java
 */
public class ProductPhotoId implements java.io.Serializable {

	private String photoUri;
	private int productId;

	public ProductPhotoId() {
	}

	public ProductPhotoId(String photoUri, int productId) {
		this.photoUri = photoUri;
		this.productId = productId;
	}

	public String getPhotoUri() {
		return this.photoUri;
	}

	public void setPhotoUri(String photoUri) {
		this.photoUri = photoUri;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductPhotoId))
			return false;
		ProductPhotoId castOther = (ProductPhotoId) other;

		return ((this.getPhotoUri() == castOther.getPhotoUri()) || (this
				.getPhotoUri() != null && castOther.getPhotoUri() != null && this
				.getPhotoUri().equals(castOther.getPhotoUri())))
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhotoUri() == null ? 0 : this.getPhotoUri().hashCode());
		result = 37 * result + this.getProductId();
		return result;
	}

}
