package it.unisalento.SWEng_project.domain;

// Generated 16-mar-2016 14.43.11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Seller generated by hbm2java
 */
public class Seller implements java.io.Serializable {

	private SellerId id;
	private User user;
	private Set shops = new HashSet(0);

	public Seller() {
	}

	public Seller(SellerId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Seller(SellerId id, User user, Set shops) {
		this.id = id;
		this.user = user;
		this.shops = shops;
	}

	public SellerId getId() {
		return this.id;
	}

	public void setId(SellerId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set getShops() {
		return this.shops;
	}

	public void setShops(Set shops) {
		this.shops = shops;
	}

}
