package it.unisalento.SWEng_project.domain;

// Generated 15-mar-2016 15.20.49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Shipment generated by hbm2java
 */
public class Shipment implements java.io.Serializable {

	private Integer id;
	private Order order;
	private String carrier;
	private String trackingCode;
	private Set products = new HashSet(0);

	public Shipment() {
	}

	public Shipment(Order order) {
		this.order = order;
	}

	public Shipment(Order order, String carrier, String trackingCode,
			Set products) {
		this.order = order;
		this.carrier = carrier;
		this.trackingCode = trackingCode;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public String getTrackingCode() {
		return this.trackingCode;
	}

	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
