package it.unisalento.SWEng_project.domain;

// Generated 15-mar-2016 15.20.49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeOfProduct generated by hbm2java
 */
public class TypeOfProduct implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String brand;
	private String model;
	private Set products = new HashSet(0);

	public TypeOfProduct() {
	}

	public TypeOfProduct(Category category, String brand, String model) {
		this.category = category;
		this.brand = brand;
		this.model = model;
	}

	public TypeOfProduct(Category category, String brand, String model,
			Set products) {
		this.category = category;
		this.brand = brand;
		this.model = model;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
