package it.unisalento.SWEng_project.domain;

// Generated 16-mar-2016 14.43.11 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String ssn;
	private String username;
	private String password;
	private Date createTime;
	private String name;
	private String surname;
	private Date dateOfBirth;
	private Set sellers = new HashSet(0);
	private Set orders = new HashSet(0);
	private AddressBook addressBook;
	private Set locations = new HashSet(0);

	public User() {
	}

	public User(String ssn, String username, String password) {
		this.ssn = ssn;
		this.username = username;
		this.password = password;
	}

	public User(String ssn, String username, String password, Date createTime,
			String name, String surname, Date dateOfBirth, Set sellers,
			Set orders, AddressBook addressBook, Set locations) {
		this.ssn = ssn;
		this.username = username;
		this.password = password;
		this.createTime = createTime;
		this.name = name;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.sellers = sellers;
		this.orders = orders;
		this.addressBook = addressBook;
		this.locations = locations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Set getSellers() {
		return this.sellers;
	}

	public void setSellers(Set sellers) {
		this.sellers = sellers;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public AddressBook getAddressBook() {
		return this.addressBook;
	}

	public void setAddressBook(AddressBook addressBook) {
		this.addressBook = addressBook;
	}

	public Set getLocations() {
		return this.locations;
	}

	public void setLocations(Set locations) {
		this.locations = locations;
	}

}
